// Generated by LiveScript 1.3.1
/*
" --------------------------------------------------
"   FileName: ndoo.block.test.ls
"       Desc: test block模块
"     Author: chenglf
"    Version: ndoo.js(v0.1b5)
" LastChange: 05/21/2014 15:32
" --------------------------------------------------
*/
(function(_n, depend){
  "use strict";
  var _, $, _vars, _func, _stor;
  _ = depend['_'];
  $ = depend['$'];
  _vars = _n.vars;
  _func = _n.func;
  _stor = _n.storage;
  _n.block('test', 'main', {
    init: function(elem, params){
      console.log('init test block');
    }
  });
  return _n;
})(this.N = this.ndoo || (this.ndoo = {}), {
  _: _,
  $: jQuery
});
/* vim: se ts=2 sts=2 sw=2 fdm=marker cc=80 et: */
