// Generated by LiveScript 1.3.1
(function(_n, depend){
  "use strict";
  var _, $, _vars, _func, _stor;
  _ = depend['_'];
  $ = depend['$'];
  _vars = _n.vars;
  _func = _n.func;
  _stor = _n.storage;
  _n.block('example3', 'block', {
    init: function(elem, params){
      var $elem;
      $elem = $(elem);
      $elem.text('block inited');
    }
  });
  return _n;
})(this.N = this.ndoo || (this.ndoo = {}), {
  _: _,
  $: jQuery
});
/* vim: se ts=2 sts=2 sw=2 fdm=marker cc=80 et: */
